//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Client_ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> Year_Of_Birth { get; set; }
    }
}
