//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istoriya
    {
        public int Istoriya_ID { get; set; }
        public string Flight_number { get; set; }
        public string Otkuda { get; set; }
        public string Kuda { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
