//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Ticket_Id { get; set; }
        public string Flight_number { get; set; }
        public string Otkuda { get; set; }
        public string Kuda { get; set; }
        public Nullable<System.TimeSpan> Vremya_otpravlenya { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Kol_svobod_biletov { get; set; }
        public Nullable<int> Runway_ID { get; set; }
        public Nullable<int> Transplantation_ID { get; set; }
        public string Otk_Count { get; set; }
        public string Kud_Count { get; set; }
    
        public virtual Runways Runways { get; set; }
        public virtual Transplantations Transplantations { get; set; }
    }
}
